"use client"
import Head from 'next/head'
import SideNavMSP from '@/components/nav'
import { Dashboard } from '@/components/dashboard'
import { SplashScreen } from '@/components/splashscreen'
import { usePathname } from "next/navigation"
import { useState, useEffect } from "react"
import { ResponsiveNav } from '@/components/nav_responsive.js'

export default function Home() {
  const pathname = usePathname();
  const isHome = pathname === "/";
  const [isLoading, setLoading] = useState(isHome)

  useEffect(() => {
    if (isLoading) return
  }, [isLoading])

  return (<>
    <Head>
      <title>😐</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div id='bg-img' className='flex flex-row min-h-screen font-sans parallax-effect'>
      {isLoading && isHome ? (
        <SplashScreen finishLoading={() => setLoading(false)}/>
      ) : (<>
        {/* <SplashScreen finishLoading={() => setLoading(false)}/> */}
        {/* <ResponsiveNav /> */}
        <SideNavMSP />
        <Dashboard />
      </>)}
    </div>
  </>)
}
