import Head from 'next/head'
import SideNavMSP from '@/components/nav'
import { Dashboard } from '@/components/dashboard'

export default function Home() {
  return (<>
    <Head>
      <title>😐</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div id='bg-img' className='flex flex-row min-h-screen font-sans parallax-effect'>
      <SideNavMSP />
      <Dashboard />
    </div>
  </>)
}
