"use client"
import Head from 'next/head'
import SideNavMSP from '@/components/nav'
import { Dashboard } from '@/components/dashboard'
import { SplashScreen } from '@/components/splashscreen'
import { usePathname } from "next/navigation"
import { useState, useEffect } from "react"
import { ResponsiveNav } from '@/components/nav_responsive.js'
import anime from "animejs"

export default function Home() {
  const pathname = usePathname();
  const isHome = pathname === "/";
  const [isLoading, setLoading] = useState(isHome)

  useEffect(() => {
    if (isLoading) return
    animate()
  }, [isLoading])

  const animate = () => {
    const loader = anime.timeline({
    })

    loader.add({
      targets: `#homepage_fadein`,
      easing: 'linear',
      duration: 2000,
      // translateX: 0.1,
      opacity: 1
    })
  }

  return (<>
    <Head>
      <title>😐</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div id='bg-img' className='flex flex-row min-h-screen parallax-effect lg:overflow-hidden'>
      {isLoading && isHome ? (
        <SplashScreen finishLoading={() => setLoading(false)} />
      ) : (<>
        {/* <SplashScreen finishLoading={() => setLoading(false)} /> */}
        {/* <ResponsiveNav /> */}
        <div id="homepage_fadein" className='opacity-0'>
          <SideNavMSP />
        </div>
        <div id="homepage_fadein" className='opacity-0'>
          <Dashboard />
        </div>
      </>)}
    </div>
  </>)
}
